### ISSUE TITLE
HW1

### ISSUE THREAD

**Issue by katebogolepova** [rtugov/globus#1]
1) Странно, вроде как ожидаешь float, а ошибка такая:
}
        catch (InputMismatchException e) {
            System.out.println("An integer number was expected! Crash!");
            return;
        }
2) Поехало форматирование
3) что будет, если разделить на 0?

**Comment by rtugov** [comment]
Hi @katebogolepova 

1. Done 
2. Done
3. В случае double / float все работало бы нормально потому что 1.0 / 0.0 давало бы результат вроде Float.POSITIVE_INFINITY. Добавил проверку на то что второй аргумент не может быть нулем.
